// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThaiHoaOfficial.Api.Data;

namespace ThaiHoaOfficial.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210829151059_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ea9b4dc-60d9-4bde-88af-07c878e9229f"),
                            CreatedDate = new DateTime(2021, 8, 29, 22, 10, 58, 233, DateTimeKind.Local).AddTicks(289),
                            Name = "Administrator",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("ec7d11f9-0a8e-4488-90e6-16837a88cdd6"),
                            CreatedDate = new DateTime(2021, 8, 29, 22, 10, 58, 233, DateTimeKind.Local).AddTicks(5316),
                            Name = "Phòng CNTT",
                            Status = 0
                        });
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe26dc1a-37da-400e-86cf-49a51dcd1554"),
                            CreatedDate = new DateTime(2021, 8, 29, 22, 10, 58, 234, DateTimeKind.Local).AddTicks(9728),
                            DateOfBirth = new DateTime(1992, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("2ea9b4dc-60d9-4bde-88af-07c878e9229f"),
                            EmailAddress = "hntduy1992@gmail.com",
                            FullName = "Hồ Ngọc Tư Duy",
                            IsMale = true,
                            PhoneNumber = "0939433628",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.User", b =>
                {
                    b.HasOne("ThaiHoaOfficial.Shared.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.Department", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
