// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThaiHoaOfficial.Api.Data;

namespace ThaiHoaOfficial.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210901153416_removeLoginMode")]
    partial class removeLoginMode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0ea1209-c1df-45cc-b713-9797d6e997d4"),
                            CreatedDate = new DateTime(2021, 9, 1, 22, 34, 15, 471, DateTimeKind.Local).AddTicks(4814),
                            Name = "Administrator",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("afa7a04c-77d7-4782-b178-8ba44111ddf9"),
                            CreatedDate = new DateTime(2021, 9, 1, 22, 34, 15, 471, DateTimeKind.Local).AddTicks(9065),
                            Name = "Phòng CNTT",
                            Status = 0
                        });
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f89735cf-6b3b-4054-a961-cc88ecae0146"),
                            CreatedDate = new DateTime(2021, 9, 1, 22, 34, 15, 473, DateTimeKind.Local).AddTicks(2743),
                            DateOfBirth = new DateTime(1992, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("d0ea1209-c1df-45cc-b713-9797d6e997d4"),
                            EmailAddress = "hntduy1992@gmail.com",
                            FullName = "Hồ Ngọc Tư Duy",
                            IsMale = true,
                            Password = "",
                            PhoneNumber = "0939433628",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.User", b =>
                {
                    b.HasOne("ThaiHoaOfficial.Shared.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.Department", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
