// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThaiHoaOfficial.Api.Data;

namespace ThaiHoaOfficial.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210831135849_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cf4de41-bd00-4baa-ab4c-eb87309eeb76"),
                            CreatedDate = new DateTime(2021, 8, 31, 20, 58, 48, 764, DateTimeKind.Local).AddTicks(2102),
                            Name = "Administrator",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("c2ee9aad-279a-435d-afed-0bb732f23998"),
                            CreatedDate = new DateTime(2021, 8, 31, 20, 58, 48, 764, DateTimeKind.Local).AddTicks(6587),
                            Name = "Phòng CNTT",
                            Status = 0
                        });
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<int>("LoginMode")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a58e194-0cb4-4838-83a3-f728253f4494"),
                            CreatedDate = new DateTime(2021, 8, 31, 20, 58, 48, 766, DateTimeKind.Local).AddTicks(573),
                            DateOfBirth = new DateTime(1992, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("0cf4de41-bd00-4baa-ab4c-eb87309eeb76"),
                            EmailAddress = "hntduy1992@gmail.com",
                            FullName = "Hồ Ngọc Tư Duy",
                            IsMale = true,
                            LoginMode = 1,
                            Password = "",
                            PhoneNumber = "0939433628",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.User", b =>
                {
                    b.HasOne("ThaiHoaOfficial.Shared.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ThaiHoaOfficial.Shared.Models.Department", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
